import { createHash } from "crypto";
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import WebSocket from "ws";

export interface HealingEvent {
  scriptId: string;
  targetDescription: string;
  oldSelector: string;
  newSelector: string;
  screenshotBase64?: string;
  status: "PENDING" | "HEALED" | "FAILED";
}

export interface TelemetryLoggerConfig {
  url?: string;
  anonKey?: string;
  projectId?: string;
  projectName?: string;
  scriptId?: string;
  scriptName?: string;
  scriptFilePath?: string;
}

/**
 * TelemetryLogger - Logs healing events to Supabase
 */
export class TelemetryLogger {
  private supabase: SupabaseClient | null = null;
  private enabled: boolean = false;
  private config: TelemetryLoggerConfig;

  constructor(config?: TelemetryLoggerConfig) {
    this.config = config || {};

    if (config?.url && config?.anonKey) {
      this.supabase = createClient(config.url, config.anonKey, {
        realtime: { transport: WebSocket as unknown as typeof globalThis.WebSocket },
      });
      this.enabled = true;
    } else if (process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY) {
      // Prefer server-side env vars when available
      this.supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
        realtime: { transport: WebSocket as unknown as typeof globalThis.WebSocket },
      });
      this.enabled = true;
    } else if (
      process.env.NEXT_PUBLIC_SUPABASE_URL &&
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    ) {
      // Fallback to NEXT_PUBLIC_* for client-side or local dev setups
      this.supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
        {
          realtime: { transport: WebSocket as unknown as typeof globalThis.WebSocket },
        }
      );
      this.enabled = true;
    }
  }

  private stableUuid(input: string): string {
    const hash = createHash("sha1").update(input).digest("hex").slice(0, 32);
    const bytes = Buffer.from(hash, "hex");

    bytes[6] = (bytes[6] & 0x0f) | 0x50;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;

    const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
    return [
      hex.slice(0, 8),
      hex.slice(8, 12),
      hex.slice(12, 16),
      hex.slice(16, 20),
      hex.slice(20, 32),
    ].join("-");
  }

  private async ensureProjectAndScriptRows(scriptId: string): Promise<void> {
    if (!this.supabase) return;

    const projectName = this.config.projectName?.trim() || "Lazarus Demo Project";
    const scriptName = this.config.scriptName?.trim() || scriptId || "Lazarus Demo Script";
    const scriptFilePath = this.config.scriptFilePath?.trim() || null;
    const projectId = this.config.projectId?.trim() || this.stableUuid(`project:${projectName}`);

    const { error: projectError } = await this.supabase.from("projects").upsert(
      [
        {
          id: projectId,
          name: projectName,
          description: `Autogenerated by Lazarus telemetry for ${scriptName}`,
        },
      ],
      { onConflict: "id" }
    );

    if (projectError) {
      console.error("[Lazarus Telemetry] Error ensuring project row:", projectError);
    }

    const { error: scriptError } = await this.supabase.from("scripts").upsert(
      [
        {
          id: scriptId,
          project_id: projectId,
          name: scriptName,
          file_path: scriptFilePath || `${scriptName}.ts`,
        },
      ],
      { onConflict: "id" }
    );

    if (scriptError) {
      console.error("[Lazarus Telemetry] Error ensuring script row:", scriptError);
    }
  }

  /**
   * Log a healing event to Supabase
   */
  async logHealing(event: HealingEvent): Promise<void> {
    if (!this.enabled || !this.supabase) {
      console.log("[Lazarus Telemetry] Telemetry disabled, skipping log");
      return;
    }

    try {
      await this.ensureProjectAndScriptRows(event.scriptId);

      const { error } = await this.supabase.from("healing_events").insert([
        {
          script_id: event.scriptId,
          target_description: event.targetDescription,
          old_selector: event.oldSelector,
          new_selector: event.newSelector,
          screenshot_base64: event.screenshotBase64 || null,
          status: event.status,
          created_at: new Date().toISOString(),
        },
      ]);

      if (error) {
        console.error("[Lazarus Telemetry] Error logging healing event:", error);
      } else {
        console.log("[Lazarus Telemetry] Event logged successfully");
      }
    } catch (error) {
      console.error("[Lazarus Telemetry] Unexpected error:", error);
    }
  }
}
